import { useEffect, useState } from 'react';

/**
 * 计算攻略 — loads the pre-rendered guide HTML generated by scripts/gen-guide.mjs.
 * To update: edit public/tutorial/*.md then run `node scripts/gen-guide.mjs`.
 */

const GUIDE_HTML = '/tutorial/guide.html';

export default function GuidePage() {
  const [html, setHtml] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    fetch(GUIDE_HTML)
      .then(r => { if (!r.ok) throw new Error(`HTTP ${r.status}`); return r.text(); })
      .then(text => setHtml(text))
      .catch(e => setError(`加载攻略失败：${e.message}`))
      .finally(() => setLoading(false));
  }, []);

  if (loading) return <div className="text-text-muted p-8 text-center">加载攻略中…</div>;
  if (error) return <div className="text-danger p-8 text-center">{error}</div>;

  return (
    <div className="card">
      <div dangerouslySetInnerHTML={{ __html: html }} />
    </div>
  );
}
